const { daysAgo, daysFromNow } = require('./helpers');

const INTELLIGENCE_PRESETS = {
  balanced: {
    linguistic: 2.8,
    logicalMathematical: 3.2,
    spatial: 2.5,
    musical: 2.2,
    bodilyKinesthetic: 3.5,
    naturalistic: 2.6,
    interpersonal: 2.9,
    intrapersonal: 3.1,
  },
  scholar: {
    linguistic: 4.2,
    logicalMathematical: 4.5,
    spatial: 3.0,
    musical: 2.0,
    bodilyKinesthetic: 2.2,
    naturalistic: 2.5,
    interpersonal: 3.0,
    intrapersonal: 3.8,
  },
  fighter: {
    linguistic: 2.0,
    logicalMathematical: 2.5,
    spatial: 2.8,
    musical: 2.0,
    bodilyKinesthetic: 4.8,
    naturalistic: 3.2,
    interpersonal: 3.0,
    intrapersonal: 2.8,
  },
  social: {
    linguistic: 3.5,
    logicalMathematical: 2.8,
    spatial: 2.5,
    musical: 3.0,
    bodilyKinesthetic: 2.5,
    naturalistic: 2.8,
    interpersonal: 4.6,
    intrapersonal: 3.2,
  },
  shadow: {
    linguistic: 3.0,
    logicalMathematical: 3.5,
    spatial: 2.5,
    musical: 2.5,
    bodilyKinesthetic: 2.8,
    naturalistic: 2.5,
    interpersonal: 2.5,
    intrapersonal: 4.5,
  },
};

const CORE_PRESETS = {
  balanced: { strength: 3.2, endurance: 3.0, agility: 2.8, flexibility: 2.6, willpower: 3.4, cardioHealth: 3.0, discipline: 3.5 },
  fighter: { strength: 4.5, endurance: 4.0, agility: 3.5, flexibility: 2.8, willpower: 3.8, cardioHealth: 3.8, discipline: 3.5 },
  scholar: { strength: 2.0, endurance: 2.5, agility: 2.2, flexibility: 2.5, willpower: 4.0, cardioHealth: 2.5, discipline: 4.2 },
};

const NOTIFICATION_DEFAULTS = {
  enableAll: true,
  workoutReminders: true,
  weeklyReport: true,
  achievements: true,
  newCourses: true,
  socialActivity: true,
  dailyQuestReminders: true,
  streakReminders: true,
  intelligenceTrainingReminders: true,
  challengeReminders: true,
  aiCoachReminders: true,
  marketplaceNotifications: true,
};

const getUsers = () => [
  {
    key: 'hunter',
    fullName: 'Sung Park',
    email: 'hunter@example.com',
    password: 'password123',
    age: 24,
    weight: 71,
    height: 178,
    gender: 'male',
    location: 'Seoul, KR',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    performanceLevel: 5,
    xp: 420,
    rank: 'C-Rank',
    classType: 'Balanced Hunter',
    avatarTier: 2,
    dayStreak: 12,
    lastCompletionDate: require('./helpers').today(),
    points: 285,
    coins: 340,
    coursesCompleted: 2,
    timeSpentHours: 18,
    weeklyGoalPercent: 72,
    onboardingComplete: true,
    hasCompletedOnboarding: true,
    fitnessGoal: 'Build strength and discipline',
    mentalGoal: 'Improve mental clarity and focus',
    selectedDevelopmentFocus: ['fitness', 'discipline', 'intelligence', 'generalGrowth'],
    preferredQuestTypes: ['mixed', 'physical', 'mental', 'reflection'],
    availableDailyTime: 30,
    availableEquipment: ['None', 'Resistance bands', 'Yoga mat'],
    reminderTime: '07:30',
    equippedAura: 'shadow_aura',
    equippedSkin: '',
    inventory: [
      { itemId: 'rhythm_core', purchasedAt: daysFromNow(-14) },
      { itemId: 'writers_scroll', purchasedAt: daysFromNow(-7) },
    ],
    intelligenceStats: INTELLIGENCE_PRESETS.balanced,
    coreStats: CORE_PRESETS.balanced,
    stats: { discipline: 72, iq: 68, strength: 65, social: 58, socialKnowledge: 55 },
    earnedBadges: [
      { badgeId: 'first_quest_complete', date: 'Apr 12' },
      { badgeId: 'streak_7', date: 'Apr 20' },
      { badgeId: 'level_5_hunter', date: 'May 10' },
      { badgeId: 'word_hunter', date: 'May 15' },
      { badgeId: 'body_awakening', date: 'May 22' },
    ],
    notificationSettings: NOTIFICATION_DEFAULTS,
    completedTests: [{ testId: 'iq_basics', score: 82, date: 'May 1' }],
  },
  {
    key: 'admin',
    fullName: 'System Admin',
    email: 'admin@system.app',
    password: 'admin123',
    age: 30,
    isAdmin: true,
    rank: 'S-Rank',
    classType: 'System Overseer',
    performanceLevel: 20,
    points: 9999,
    xp: 1950,
    coins: 5000,
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    onboardingComplete: true,
    hasCompletedOnboarding: true,
    intelligenceStats: {
      linguistic: 5, logicalMathematical: 5, spatial: 5, musical: 5,
      bodilyKinesthetic: 5, naturalistic: 5, interpersonal: 5, intrapersonal: 5,
    },
    coreStats: { strength: 5, endurance: 5, agility: 5, flexibility: 5, willpower: 5, cardioHealth: 5, discipline: 5 },
    notificationSettings: NOTIFICATION_DEFAULTS,
  },
  {
    key: 'nova',
    fullName: 'Nova Chen',
    email: 'nova@example.com',
    password: 'password123',
    age: 22,
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    performanceLevel: 7,
    xp: 680,
    rank: 'B-Rank',
    classType: 'Social Leader',
    points: 410,
    coins: 220,
    dayStreak: 5,
    onboardingComplete: true,
    hasCompletedOnboarding: true,
    intelligenceStats: INTELLIGENCE_PRESETS.social,
    coreStats: { strength: 2.5, endurance: 2.8, agility: 3.0, flexibility: 3.2, willpower: 3.5, cardioHealth: 3.0, discipline: 3.2 },
    selectedDevelopmentFocus: ['social', 'communication'],
    preferredQuestTypes: ['social', 'mixed'],
    availableDailyTime: 45,
  },
  {
    key: 'kai',
    fullName: 'Kai Mendez',
    email: 'kai@example.com',
    password: 'password123',
    age: 28,
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    performanceLevel: 8,
    xp: 790,
    rank: 'B-Rank',
    classType: 'Strength Fighter',
    points: 520,
    coins: 180,
    dayStreak: 21,
    onboardingComplete: true,
    hasCompletedOnboarding: true,
    intelligenceStats: INTELLIGENCE_PRESETS.fighter,
    coreStats: CORE_PRESETS.fighter,
    selectedDevelopmentFocus: ['fitness'],
    preferredQuestTypes: ['physical'],
    availableDailyTime: 60,
    availableEquipment: ['Dumbbells', 'Full gym'],
  },
  {
    key: 'mira',
    fullName: 'Mira Okonkwo',
    email: 'mira@example.com',
    password: 'password123',
    age: 26,
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    performanceLevel: 6,
    xp: 550,
    rank: 'C-Rank',
    classType: 'Word Scholar',
    points: 380,
    coins: 290,
    dayStreak: 9,
    onboardingComplete: true,
    hasCompletedOnboarding: true,
    intelligenceStats: INTELLIGENCE_PRESETS.scholar,
    coreStats: CORE_PRESETS.scholar,
    selectedDevelopmentFocus: ['intelligence', 'communication'],
    preferredQuestTypes: ['mental', 'reflection'],
    availableDailyTime: 30,
  },
  {
    key: 'newbie',
    fullName: 'Alex Rivers',
    email: 'newbie@example.com',
    password: 'password123',
    age: 19,
    avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
    performanceLevel: 1,
    xp: 15,
    rank: 'E-Rank',
    classType: 'Balanced Hunter',
    points: 10,
    coins: 25,
    dayStreak: 0,
    onboardingComplete: false,
    intelligenceStats: {
      linguistic: 1, logicalMathematical: 1, spatial: 1, musical: 1,
      bodilyKinesthetic: 1, naturalistic: 1, interpersonal: 1, intrapersonal: 1,
    },
    coreStats: CORE_PRESETS.balanced,
    selectedDevelopmentFocus: ['generalGrowth'],
  },
];

const getCourses = () => [
  {
    title: 'System Morning Protocol',
    description: 'Wake-up rituals: hydration, planning, and a no-phone focus block to start the day with discipline.',
    workoutType: 'Discipline',
    difficulty: 'Easy',
    levelRequirement: 1,
    duration: '20 Minutes',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400',
    isStandard: true,
    rules: ['Complete all tasks before 10 AM', 'Log completion in the app'],
    tasks: [
      { title: 'Hydrate', description: 'Drink one full glass of water after waking', status: 'done', lastCompletedDate: daysAgo(0) },
      { title: 'Daily Quest Board', description: 'Write top 3 priorities for today', status: 'pending' },
      { title: 'No-phone Focus', description: 'No social media for the first 30 minutes', status: 'pending' },
    ],
  },
  {
    title: 'Scholar Grind Session',
    description: 'Deep work and recall drills for linguistic and logical intelligence growth.',
    workoutType: 'Study',
    difficulty: 'Medium',
    levelRequirement: 2,
    duration: '45 Minutes',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    isStandard: true,
    tasks: [
      { title: 'Deep Work Block', description: '40-minute uninterrupted study session', status: 'done' },
      { title: 'Recall Drill', description: 'Summarize learning in 5 bullet points', status: 'pending' },
      { title: 'Vocabulary Capture', description: 'Write 5 new words with definitions', status: 'pending' },
    ],
  },
  {
    title: 'Hunter Body Conditioning',
    description: 'Bodyweight circuit and mobility for bodily-kinesthetic development.',
    workoutType: 'Fitness',
    difficulty: 'Medium',
    levelRequirement: 2,
    duration: '30 Minutes',
    image: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400',
    isStandard: true,
    tasks: [
      { title: 'Bodyweight Circuit', description: '3 rounds: 10 push-ups, 15 squats, 30s plank', status: 'pending' },
      { title: 'Recovery Stretch', description: '10 minutes mobility and breathing', status: 'pending' },
    ],
  },
  {
    title: 'Spatial Architect Lab',
    description: 'Visualization, sketching, and environment organization challenges.',
    workoutType: 'Skill Building',
    difficulty: 'Easy',
    levelRequirement: 1,
    duration: '25 Minutes',
    image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1a83d?w=400',
    isStandard: true,
    tasks: [
      { title: 'Workspace Sketch', description: 'Draw or diagram your ideal workspace', status: 'pending' },
      { title: 'Memory Map', description: 'Create a mental map of your weekly schedule', status: 'pending' },
    ],
  },
  {
    title: 'Rhythm Monk Practice',
    description: 'Musical intelligence through rhythm, listening focus, and breath coordination.',
    workoutType: 'Mental Focus',
    difficulty: 'Easy',
    levelRequirement: 1,
    duration: '15 Minutes',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400',
    isStandard: true,
    tasks: [
      { title: 'Rhythmic Breathing', description: '3 minutes inhale/exhale on a steady beat', status: 'pending' },
      { title: 'Listening Focus', description: 'One song, eyes closed, no multitasking', status: 'pending' },
    ],
  },
  {
    title: 'Nature Ranger Walk',
    description: 'Outdoor observation, hydration awareness, and naturalistic habits.',
    workoutType: 'Health',
    difficulty: 'Easy',
    levelRequirement: 1,
    duration: '30 Minutes',
    image: 'https://images.unsplash.com/photo-1441974231530-c3367d4c0a83?w=400',
    isStandard: true,
    tasks: [
      { title: 'Nature Walk', description: '15-minute walk outdoors with observation notes', status: 'pending' },
      { title: 'Hydration Log', description: 'Track water intake for the day', status: 'pending' },
    ],
  },
  {
    title: 'Productivity Assassin Sprint',
    description: 'High-output task batching for logical and discipline stats.',
    workoutType: 'Productivity',
    difficulty: 'Hard',
    levelRequirement: 4,
    duration: '60 Minutes',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400',
    isStandard: true,
    tasks: [
      { title: 'Priority Strike', description: 'Finish hardest task first — no switching', status: 'pending' },
      { title: 'Time Block Audit', description: 'Review where your hour went', status: 'pending' },
      { title: 'Ship One Result', description: 'Deliver one measurable outcome today', status: 'pending' },
    ],
  },
  {
    title: 'Inner Shadow Reflection',
    description: 'Journaling and intrapersonal growth for willpower and self-awareness.',
    workoutType: 'Daily Life',
    difficulty: 'Easy',
    levelRequirement: 1,
    duration: '20 Minutes',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    isStandard: true,
    tasks: [
      { title: 'Morning Journal', description: 'Write 5 lines on what you want to improve', status: 'done' },
      { title: 'Mood Check', description: 'Rate energy 1–10 and note one trigger', status: 'pending' },
      { title: 'Evening Review', description: 'What went well? What to change tomorrow?', status: 'pending' },
    ],
  },
  {
    title: 'Social Spark Challenge',
    description: 'Interpersonal missions: connection, empathy, and community interaction.',
    workoutType: 'Daily Life',
    difficulty: 'Medium',
    levelRequirement: 2,
    duration: '25 Minutes',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
    isStandard: true,
    tasks: [
      { title: 'Positive Message', description: 'Send an encouraging message to someone', status: 'pending' },
      { title: 'Active Listening', description: '5-minute conversation with full attention', status: 'pending' },
    ],
  },
];

const getChallenges = () => {
  const now = new Date();
  return [
    {
      title: '7-Day Focus Awakening',
      description: 'Complete one focused study or logic task every day for 7 days.',
      category: 'Mental Focus',
      difficulty: 'Medium',
      expReward: 120,
      levelRequirement: 2,
      startDate: now,
      expiryDate: daysFromNow(7),
      status: 'open',
      tasks: [
        { title: 'Daily Deep Work', description: 'One uninterrupted 25+ minute focus block' },
        { title: 'Reflection Note', description: 'Log one lesson learned' },
      ],
    },
    {
      title: 'Logic Awakening Trial',
      description: 'Solve puzzles and planning challenges to boost logical-mathematical intelligence.',
      category: 'Study',
      difficulty: 'Medium',
      expReward: 150,
      levelRequirement: 3,
      startDate: now,
      expiryDate: daysFromNow(10),
      status: 'open',
      tasks: [
        { title: 'Daily Puzzle', description: 'Complete one logic puzzle or planning exercise' },
        { title: 'Strategy Write-up', description: 'Document your approach in 3 steps' },
      ],
    },
    {
      title: 'Strength Path Week',
      description: 'Daily movement for bodily-kinesthetic growth.',
      category: 'Fitness',
      difficulty: 'Hard',
      expReward: 200,
      levelRequirement: 4,
      startDate: now,
      expiryDate: daysFromNow(7),
      status: 'open',
      tasks: [
        { title: 'Movement Quest', description: '15+ minutes of intentional exercise' },
        { title: 'Mobility Reset', description: '5-minute stretch cooldown' },
      ],
    },
    {
      title: 'Green Hunter Challenge',
      description: 'Nature walks, hydration, and environment awareness.',
      category: 'Health',
      difficulty: 'Easy',
      expReward: 80,
      levelRequirement: 1,
      startDate: now,
      expiryDate: daysFromNow(5),
      status: 'open',
      tasks: [
        { title: 'Outdoor Observation', description: '3 minutes noticing your environment' },
        { title: 'Hydration Goal', description: 'Meet daily water target' },
      ],
    },
    {
      title: 'Team Hunter Social Week',
      description: 'Build interpersonal intelligence through daily social missions.',
      category: 'Daily Life',
      difficulty: 'Medium',
      expReward: 100,
      levelRequirement: 2,
      startDate: now,
      expiryDate: daysFromNow(7),
      status: 'open',
      tasks: [
        { title: 'Connection Task', description: 'Meaningful interaction with one person' },
        { title: 'Empathy Note', description: 'Write how someone else might feel today' },
      ],
    },
  ];
};

const buildDailyQuestTasks = (completedIndexes = []) => {
  const tasks = [
    {
      title: 'Body Activation',
      description: '3 sets of 10 squats and 10 push-ups.',
      category: 'physical',
      intelligenceType: 'bodilyKinesthetic',
      coreStatType: 'strength',
      durationMinutes: 8,
      xpReward: 15,
      coinsReward: 5,
      difficulty: 'Beginner',
      instructions: 'Warm up first. Rest 30 seconds between sets.',
      proofType: 'manual',
    },
    {
      title: 'Logic Focus',
      description: 'Solve one short logic puzzle or planning challenge.',
      category: 'logical',
      intelligenceType: 'logicalMathematical',
      coreStatType: 'discipline',
      durationMinutes: 7,
      xpReward: 10,
      coinsReward: 3,
      difficulty: 'Beginner',
      instructions: 'Write your answer before checking the solution.',
      proofType: 'text',
    },
    {
      title: 'Word Craft',
      description: 'Write 5 sentences about your main goal today.',
      category: 'linguistic',
      intelligenceType: 'linguistic',
      coreStatType: 'willpower',
      durationMinutes: 5,
      xpReward: 10,
      coinsReward: 2,
      difficulty: 'Easy',
      instructions: 'Use clear, specific language.',
      proofType: 'text',
    },
    {
      title: 'Inner Reflection',
      description: 'Write 3 lines about what you want to improve today.',
      category: 'reflection',
      intelligenceType: 'intrapersonal',
      coreStatType: 'willpower',
      durationMinutes: 5,
      xpReward: 10,
      coinsReward: 2,
      difficulty: 'Easy',
      instructions: 'Be honest and specific.',
      proofType: 'text',
    },
    {
      title: 'Rhythm Breath',
      description: '3 minutes of breathing coordinated to a steady beat.',
      category: 'musical',
      intelligenceType: 'musical',
      coreStatType: 'discipline',
      durationMinutes: 3,
      xpReward: 8,
      coinsReward: 2,
      difficulty: 'Easy',
      instructions: 'Use a metronome app or tap your foot.',
      proofType: 'timer',
    },
  ];
  return tasks.map((t, i) => ({
    ...t,
    completed: completedIndexes.includes(i),
    completedAt: completedIndexes.includes(i) ? new Date() : undefined,
  }));
};

const getMarketplaceItems = () => [
  { itemId: 'logic_crystal', name: 'Logic Crystal', description: 'Boosts logical quest XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'logicalMathematical', boostPercent: 10, priceCoins: 80, icon: 'diamond-outline', rarity: 'rare' },
  { itemId: 'writers_scroll', name: "Writer's Scroll", description: 'Boosts linguistic quest XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'linguistic', boostPercent: 10, priceCoins: 75, icon: 'document-text-outline', rarity: 'rare' },
  { itemId: 'shadow_aura', name: 'Shadow Aura', description: 'Boosts intrapersonal XP by 10%', type: 'aura', intelligenceBoost: 'intrapersonal', boostPercent: 10, priceCoins: 120, icon: 'moon-outline', rarity: 'epic' },
  { itemId: 'nature_cloak', name: 'Nature Cloak', description: 'Boosts naturalistic XP by 10%', type: 'skin', intelligenceBoost: 'naturalistic', boostPercent: 10, priceCoins: 90, icon: 'leaf-outline', rarity: 'rare' },
  { itemId: 'rhythm_core', name: 'Rhythm Core', description: 'Boosts musical XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'musical', boostPercent: 10, priceCoins: 70, icon: 'musical-notes-outline', rarity: 'common' },
  { itemId: 'warrior_gloves', name: 'Warrior Gloves', description: 'Boosts bodily-kinesthetic XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'bodilyKinesthetic', boostPercent: 10, priceCoins: 85, icon: 'fitness-outline', rarity: 'rare' },
  { itemId: 'spatial_lens', name: 'Spatial Lens', description: 'Boosts spatial quest XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'spatial', boostPercent: 10, priceCoins: 78, icon: 'eye-outline', rarity: 'rare' },
  { itemId: 'social_emblem', name: 'Social Emblem', description: 'Boosts interpersonal XP by 10%', type: 'intelligence_booster', intelligenceBoost: 'interpersonal', boostPercent: 10, priceCoins: 82, icon: 'people-outline', rarity: 'rare' },
  { itemId: 'discipline_sigil', name: 'Discipline Sigil', description: 'Discipline buff for 24 hours', type: 'discipline_buff', boostPercent: 15, priceCoins: 100, icon: 'shield-outline', rarity: 'epic' },
  { itemId: 'xp_amplifier', name: 'XP Amplifier', description: '+20% XP on your next daily quest', type: 'xp_booster', boostPercent: 20, priceCoins: 150, icon: 'flash-outline', rarity: 'legendary' },
  { itemId: 'focus_elixir', name: 'Focus Elixir', description: '+15% XP on mental and reflection tasks', type: 'focus_booster', boostPercent: 15, priceCoins: 95, icon: 'beaker-outline', rarity: 'epic' },
  { itemId: 'hunter_frame_gold', name: 'Gold Hunter Frame', description: 'Legendary badge frame cosmetic', type: 'badge_frame', boostPercent: 0, priceCoins: 200, icon: 'ribbon-outline', rarity: 'legendary' },
  { itemId: 'system_theme_dark', name: 'System Dark Theme', description: 'Premium dark teal dashboard theme', type: 'theme', boostPercent: 0, priceCoins: 250, icon: 'color-palette-outline', rarity: 'legendary' },
  { itemId: 'awakened_skin', name: 'Awakened Hunter Skin', description: 'Avatar skin — Awakened tier aesthetic', type: 'skin', boostPercent: 0, priceCoins: 300, icon: 'person-outline', rarity: 'legendary' },
];

module.exports = {
  getUsers,
  getCourses,
  getChallenges,
  getMarketplaceItems,
  buildDailyQuestTasks,
  INTELLIGENCE_PRESETS,
};
